#### transform.py実装前確認

01_「会社名」項目の確認

In [2]:
import pandas as pd

# スクレイピング結果csvを読み込んで、「会社名」データ確認
df = pd.read_csv("/app/data/rikunabi.csv")

In [ ]:
# 会社名の表記確認
print(f"先頭20件:\n{df['会社名'].head(20)}")
print("------------------------------------------------------")
print(f"会社名の出現回数:\n{df['会社名'].value_counts().head(30)}")
print("------------------------------------------------------")
print(f"末尾20件:\n{df['会社名'].tail(20)}")

In [3]:
# ノイズや余計な情報の混入
print(
    f"ノイズ混入件数: {df['会社名'].str.contains('本社|支店|本店|営業所| 東京| 大阪| 名古屋', na=False).sum()}"
)

# ノイズや余計な情報の混入確認
df[df["会社名"].str.contains("本社|支店|本店|営業所| 東京| 大阪| 名古屋", na=False)]

ノイズ混入件数: 6

,会社名,仕事内容,求めている人材,職場環境,勤務地,給与,勤務時間,休日・休暇,待遇・福利厚生,試用期間,その他,仕事に関するPR,仕事の特徴
98,パーソルビジネスプロセスデザイン株式会社 東京支店,仕事内容: ■業務内容（SQLデータハンドリング業務） * データ抽出・クエリ作成：SQLで...,求める人材: ■ 必須要件 * SQLを用いたデータの連携、抽出、加工経験をお持ちの方 * ...,NaN,東京都港区赤坂3-3-3住友生命赤坂ビル9F パーソルビジネスプロセスデザイン株式会社 東京...,月給30万円～45万円 給与: 予定年収：500万～650万（残業20h想定） 想定月給：3...,固定時間制 勤務時間・曜日: 標準的な勤務時間帯9:00～18:00（休憩時間60分） コア...,休暇・休日: 完全週休2日制（休日は土日祝日） 年間有給休暇10日～20日（下限日数は、入社...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生: ＜各手当・制...,試用期間あり 試用期間：3か月 試用期間中の労働条件：同条件,その他: 求人ID：356 職業紹介事業者：株式会社イーチキャリア 【事業内容】 有料職業紹...,デジタルマーケ領域でのSQLを用いたデータ抽出・加工・分析を中心に、BIツールやMAツールを...,在宅OK駅近5分以内
99,株式会社 プロトシステム 東京本社,仕事内容: データアナリスト・データエンジニアとして業務をお任せ致します。 ※スキルや経験、...,求める人材: ▼必須条件 未経験OK * Excelを使用した経験がある方 * データ領域で...,NaN,東京都千代田区二番町12-3グレイス麹町6階グレイス麹町6階 株式会社 プロトシステム 東京...,"月給25万円～27万1800円 給与: 固定残業代あり：月給 ￥250,000 〜 ￥271...",固定時間制 勤務時間・曜日: 09:00~18:00 月間平均残業時間：10時間以下,休暇・休日: 休⽇：土⽇祝休み 年間休⽇：125⽇ 休暇制度：年末年始休暇、夏季休暇、GW休...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生: * 交通費全...,試用期間あり 試用期間：3か月 試用期間中の労働条件：同条件,その他: 求人ID：355 職業紹介事業者：株式会社イーチキャリア 【事業内容】 有料職業紹...,プロトシステムでは、未経験から挑戦できるデータエンジニアを募集しています。データの分析や可視...,在宅OK駅近5分以内
164,アイフル株式会社 東京,仕事内容: 業務内容 IT金融グループの実現に向けてエンジニア/デザイナー/データアナリスト...,求める人材: 必須スキル・経験 ・WEBシステムの開発経験5年以上 ・設計、開発、テスト、保...,NaN,東京都中央区銀座一丁目６番２号LIFECARD銀座ビル アイフル株式会社 東京 勤務地: 東...,"年俸600万円～800万円 給与: 年収 6,000,000 円 - 8,000,000円 ...",固定時間制 勤務時間・曜日: 平日9:00~18:00（休憩時間60分含む） スーパーフレッ...,休暇・休日: 年間休日127日(2023年度) ・完全週休2日制（休日は土日祝/配属部署によ...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生: ＜福利厚生＞...,試用期間なし,その他: 本求人は、サーバーフリー株式会社による 有料職業紹介サービスを通じてご案内する求人...,★東京/WEBエンジニア/自社内開発/プライム上場/リモートワーク可/リーダー ※スーパーフ...,在宅OK
171,アイフル株式会社 東京,仕事内容: 業務内容 IT金融グループの実現に向けてエンジニア/デザイナー/データアナリスト...,求める人材: 必須スキル・経験 【必須】 ■スマホアプリ開発に強い興味をお持ちの方 ■自ら学...,NaN,東京都中央区銀座一丁目６番２号LIFECARD銀座ビル アイフル株式会社 東京 勤務地: 東...,"年俸420万円～800万円 給与: 年収 4,200,000 円 - 8,000,000円 ...",固定時間制 勤務時間・曜日: 平日9:00~18:00（休憩時間60分含む） スーパーフレッ...,休暇・休日: 年間休日127日(2023年度) ・完全週休2日制（休日は土日祝/配属部署によ...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生: ＜福利厚生＞...,試用期間なし,その他: 本求人は、サーバーフリー株式会社による 有料職業紹介サービスを通じてご案内する求人...,★【スマホアプリエンジニア】東京/リモートワーク×フルフレックス/自社プロダクト/モダンな環...,在宅OK
177,アイフル株式会社 東京,仕事内容: 業務内容 ■IT企業への変革に向けてエンジニア/デザイナー/データアナリストを自...,求める人材: 必須スキル・経験 【必須】 ■Javaでの開発経験 ※SIerのご出身者も歓迎...,NaN,東京都港区芝2-31-19バンザイビル3F アイフル株式会社 東京 勤務地: 東京都港区芝2...,"年俸500万円～750万円 給与: 年収 5,000,000 円 - 7,500,000円 ...",固定時間制 勤務時間・曜日: 平日9:00~18:00（休憩時間60分含む） 時間外労働あり...,休暇・休日: 年間休日127日(2023年度) ・完全週休2日制（休日は土日祝/配属部署によ...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生: ＜福利厚生＞...,試用期間なし,その他: 本求人は、サーバーフリー株式会社による 有料職業紹介サービスを通じてご案内する求人...,★東京/アジャイル開発エンジニア/プライム上場/副業OK/残業少,NaN
180,アイフル株式会社 東京,仕事内容: 業務内容 IT金融グループの実現に向けてエンジニア/デザイナー/データアナリスト...,求める人材: 必須スキル・経験 WEBシステム開発経験（言語不問）をお持ちの方 歓迎スキル・...,NaN,東京都中央区銀座一丁目６番２号LIFECARD銀座ビル アイフル株式会社 東京 勤務地: 東...,"年俸420万円～600万円 給与: 年収 4,200,000 円 - 6,000,000円 ...",固定時間制 勤務時間・曜日: 平日9:00~18:00（休憩時間60分含む） スーパーフレッ...,休暇・休日: 年間休日127日(2023年度) ・完全週休2日制（休日は土日祝/配属部署によ...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生: ＜福利厚生＞...,試用期間なし,その他: 本求人は、サーバーフリー株式会社による 有料職業紹介サービスを通じてご案内する求人...,★東京/WEBエンジニア/自社内開発/プライム上場/リモートワーク可 ※スーパーフレックスタ...,在宅OK

In [ ]:
# 欠損値・異常値・空文字の確認
print(f"欠損値の件数: {df['会社名'].isna().sum()}")
print(f"空文字の件数: {df['会社名'].str.strip().eq('').sum()}")
print(
    f"異常値の件数: {
        df['会社名'].str.contains(r'^[0-9]|^[A-Za-z]', regex=True, na=False).sum()
    }"
)

欠損値の件数: 0
空文字の件数: 0
異常値の件数: 23

In [4]:
# 異常値の確認
df[df["会社名"].str.contains(r"^[0-9]|^[A-Za-z]", regex=True, na=False)]

,会社名,仕事内容,求めている人材,職場環境,勤務地,給与,勤務時間,休日・休暇,待遇・福利厚生,試用期間,その他,仕事に関するPR,仕事の特徴
12,LINEヤフー株式会社,企業名 ＬＩＮＥヤフー株式会社 求人名 【バックエンドエンジニア】ソーシャルコマース(LIN...,"必要な経験・能力等 【必須】■Java, KotlinでのWebアプリケーション開発経験（5...",NaN,東京都千代田区 LINEヤフー株式会社 予定勤務地 東京都千代田区 勤務地 勤務地① 事業所...,"月給53万3000円～80万1000円 想定年収 800万円～1,200万円 雇用形態 正社...",フレックスタイム制度 就業時間 （1日あたり所定労働時間07時間45分）フレックスタイム制あ...,休日 休日：121日 （内訳） 完全週休二日制 土曜 日曜 祝日 年末年始7日 その他（※祝...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 制度、設備 在宅勤務 （一部従...,試用期間あり 試用期間3ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,★マネージャー候補★ ソーシャルコマースのサービス開発・運用・保守業務をご担当いただきます。...,副業・WワークOK年間休日120日以上資格取得支援あり転勤なし時短勤務あり在宅OK完全週休2...
19,ClipLine株式会社,企業名 ＣｌｉｐＬｉｎｅ株式会社 求人名 【データエンジニア】SaaS/在宅勤務可/累計調達...,必要な経験・能力等 【何れか必須】■SQL/R/Python等を用いた分析・開発経験 ■アプ...,配属先情報 3名 執行役員1名 他部署との兼任2名 ※データエンジニア専任としての募集となります！,東京都千代田区神田紺屋町15グランファースト神田紺屋町5F ClipLine株式会社 予定勤...,"月給56万9380円以上 想定年収 700万円～1,200万円 雇用形態 正社員 期間の定め...",フレックスタイム制度 就業時間 （1日あたり所定労働時間08時間）フレックスタイム制あり（コ...,休日 休日：120日 （内訳） 土曜 日曜 祝日 年末年始5日 その他（） 有給休暇：有（～...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 制度、設備 在宅勤務 （全従業...,試用期間あり 試用期間3ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,■全国チェーン展開する顧客に向け、短尺動画を通して本部と現場が双方向にやり取りできる「ABI...,業界未経験歓迎資格取得支援あり転勤なし在宅OK土日祝休み服装自由
21,Sky株式会社,企業名 Ｓｋｙ株式会社 求人名 ★【東京】データ分析・生成AI基盤構築エンジニア[データエン...,必要な経験・能力等 【必須】■データ分析基盤システム上のソフトウェア設計・開発のご経験 ■デ...,配属先情報 クライアント・システム開発事業部 ICTソリューション事業部 SI部,東京都港区港南2丁目18番1号 JR品川イーストビル9階 Sky株式会社 予定勤務地 東京都...,月給31万円以上 想定年収 560万円～900万円 雇用形態 正社員 期間の定め：無 賃金形...,変形労働時間制 就業時間 09:00～17:30（1日あたり所定労働時間07時間45分） 休...,休日 休日：120日 （内訳） 日曜 祝日 その他（リフレッシュDAY、バースデー休暇） 有...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 制度、設備 時短制度 （一部従...,試用期間なし,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,DXが加速されていく市場において、データ分析基盤を構成するデータレイクやDWH（データウェア...,業界未経験歓迎資格取得支援あり月平均残業時間20時間以内時短勤務あり退職金あり
22,GO株式会社,企業名 ＧＯ株式会社 求人名 【データアナリスト（AI技術開発部）】フルリモートOK/タクシ...,必要な経験・能力等 【すべて必須】■回帰・分類・クラスタリング手法を使用した分析業務の実務経...,配属先情報 AI技術開発部 分析グループ（現在は4名の組織です） 国内のフルリモート可能：h...,東京都港区麻布台1-3-1麻布台ヒルズ森JPタワー23階 GO株式会社 予定勤務地 東京都港...,"月給50万円以上 想定年収 600万円～1,200万円 雇用形態 正社員 期間の定め：無 賃...",フレックスタイム制度 就業時間 （1日あたり所定労働時間07時間45分）フレックスタイム制あ...,休日 休日：120日 （内訳） 完全週休二日制 土曜 日曜 祝日 その他（年末年始/慶弔/介...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 制度、設備 在宅勤務 （全従業...,試用期間あり 試用期間3ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,各種サービスを通じて発生した交通情報ビッグデータから、身近な交通を進化させるための仮説構築・...,業界未経験歓迎転勤なし在宅OK完全週休2日制土日祝休み服装自由
23,Sky株式会社,企業名 Ｓｋｙ株式会社 求人名 ★【東京】データ分析・生成AI基盤構築エンジニア[生成AI開...,必要な経験・能力等 【いずれか必須】■クラウド上で動作するWebアプリケーションのソフトウェ...,配属先情報 クライアント・システム開発事業部 ＩＣＴソリューション事業部 ＳＩ部,東京都港区港南2丁目18番1号 JR品川イーストビル9階 Sky株式会社 予定勤務地 東京都...,月給31万円以上 想定年収 560万円～900万円 雇用形態 正社員 期間の定め：無 賃金形...,変形労働時間制 就業時間 09:00～17:30（1日あたり所定労働時間07時間45分） 休...,休日 休日：120日 （内訳） 日曜 祝日 その他（リフレッシュDAY、バースデー休暇） 有...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 制度、設備 時短制度 （一部従...,試用期間なし,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,生成ＡＩを活用したシステムを構成する、システムバックエンド機能の設計・開発、各種データを管理...,業界未経験歓迎資格取得支援あり月平均残業時間20時間以内時短勤務あり退職金あり
29,iFIND株式会社,企業名 ｉＦＩＮＤ株式会社 求人名 【渋谷区/データアナリスト】★アイリスオーヤマの関連会社...,必要な経験・能力等 【必須】・社内外のステークホルダーと円滑にビジネス要件を整理できるロジカ...,NaN,東京都渋谷区神宮前1-10-29Tripeaks神宮前Bldg3階 iFIND株式会社 予定...,月給32万円～40万円 想定年収 450万円～800万円 雇用形態 正社員 期間の定め：無 ...,フレックスタイム制度 就業時間 （1日あたり所定労働時間08時間）フレックスタイム制あり（コ...,休日 休日：124日 （内訳） 土曜 日曜 祝日 その他（会社カレンダーに準ずる） 有給休暇...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 その他制度 退職金：有 社会保...,試用期間あり 試用期間3ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,■アイリスオーヤマの関連企業。クライアントビジネス部門のニーズ、既存のデータ基盤上でデータ集...,業界未経験歓迎年間休日120日以上転勤なし退職金あり土日祝休み
33,GMOインターネットグループ株式会社,企業名 ＧＭＯインターネットグループ株式会社 求人名 【機械学習エンジニア】CTO直下/Fi...,必要な経験・能力等 【必須】■機械学習を実際に使って課題を解決した経験 ■アプリケーション開...,配属先情報 次世代システム研究室 第1研究開発グループ：プロジェクト毎に7～8名の チーム。...,東京都渋谷区桜丘町26番1号セルリアンタワー GMOインターネットグループ株式会社 予定勤務...,月給58万4063円以上 想定年収 700万円～800万円 雇用形態 正社員 期間の定め：無...,固定時間制 就業時間 10:00～19:00（1日あたり所定労働時間08時間） 休憩：60分...,休日 休日：120日 （内訳） 完全週休二日制 土曜 日曜 祝日 夏季5日 年末年始6日 そ...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 制度、設備 在宅勤務 （一部従...,試用期間あり 試用期間3ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,当グループの事業領域で注力するスタートアップやグループ横断のプロジェクトのいずれかにまず参加...,業界未経験歓迎転勤なし時短勤務あり在宅OK完全週休2日制土日祝休み服装自由
42,FPTソフトウェアジャパン株式会社,企業名 ＦＰＴソフトウェアジャパン株式会社 求人名 FAI【AIエンジニア・データエンジニア...,必要な経験・能力等 【必須（3年以上）】■ビジネスレベルの日本語力 ■AI・アナリティクス関...,配属先情報 社内はベトナム籍を中心に様々な国籍の方が在籍しております。公用語は日本語です（日...,東京都港区芝公園1-7-6 KDX浜松町プレイス6階 FPTソフトウェアジャパン株式会社 予...,"月給50万円以上 想定年収 800万円～1,500万円 雇用形態 正社員 期間の定め：無 賃...",固定時間制 就業時間 09:00～18:00（1日あたり所定労働時間08時間） 休憩：60分...,休日 休日：125日 （内訳） 完全週休二日制 土曜 日曜 祝日 その他（夏季休暇、年末年始...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 制度、設備 継続雇用制度(再雇...,試用期間あり 試用期間6ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,データ・AIに関するスキルを持って、生成AIや画像AI、予測AIなどのAI案件に従事していた...,業界未経験歓迎年間休日120日以上退職金あり完全週休2日制土日祝休み
57,AMBL株式会社,企業名 ＡＭＢＬ株式会社 求人名 【11/1～2/1入社限定】データアナリスト/基盤構築エン...,必要な経験・能力等 【必須】■IT業界での就業経験（2年以上目安） 【いずれか必須(1年以上...,配属先情報 イノベーション事業本部 データサイエンス事業部,東京都港区赤坂9-7-1ミッドタウン・タワー32階（本社※2025年11月に移転） AMBL...,月給25万3000円以上 想定年収 400万円～650万円 雇用形態 正社員 期間の定め：無...,フレックスタイム制度 就業時間 （1日あたり所定労働時間08時間）フレックスタイム制あり（コ...,休日 休日：125日 （内訳） 完全週休二日制 土曜 日曜 祝日 夏季3日 その他（慶弔/時...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 制度、設備 在宅勤務 （全従業...,試用期間あり 試用期間3ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,【概要】多様な業界で、データ分析基盤の構築から顧客分析・需要予測・価格最適化・市場/売上分析...,副業・WワークOK年間休日120日以上資格取得支援あり転勤なし時短勤務あり在宅OK完全週休2...
70,NSW株式会社,企業名 ＮＳＷ株式会社 求人名 [SVBI]【未経験可】データマネジメントエンジニア【独立系...,必要な経験・能力等 【必須】■ITエンジニア経験3年以上(開発、設計、構築、運用など) ☆デ...,配属先情報 サービスソリューション事業本部 【配属予定の組織構成】 約80名（20代：50%...,東京都渋谷区桜丘町31-15 JMFビル渋谷02 NSW株式会社 予定勤務地 東京都渋谷区 ...,月給28万5000円～35万3000円 想定年収 515万円～650万円 雇用形態 正社員 ...,フレックスタイム制度 就業時間 （1日あたり所定労働時間08時間）フレックスタイム制あり（コ...,休日 休日：124日 （内訳） 完全週休二日制 土曜 日曜 祝日 年末年始5日 その他（長期...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 その他制度 退職金：有 社会保...,試用期間あり 試用期間3ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,エンジニアとして、顧客のデータ戦略を成功に導くために、データ基盤構築やデータ分析、データ活用...,業界未経験歓迎年間休日120日以上退職金あり完全週休2日制土日祝休み
103,Peach Aviation株式会社,企業名 Ｐｅａｃｈ Ａｖｉａｔｉｏｎ株式会社 求人名 社内SE/ビジネスアナリスト・ITスペ...,必要な経験・能力等 【必須】■ITに関する業務経験があること ■ベンダーコントロールの経験が...,NaN,大阪府泉佐野市 Peach Aviation株式会社 予定勤務地 大阪府泉佐野市 勤務地 勤...,月給25万円以上 想定年収 300万円～700万円 雇用形態 正社員 期間の定め：無 賃金形...,固定時間制 就業時間 09:00～18:00（1日あたり所定労働時間08時間） 休憩：60分...,休日 休日：122日 （内訳） 完全週休二日制 土曜 日曜 祝日 その他（年間休日数は会社カ...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 制度、設備 リモートワーク可 ...,試用期間あり 試用期間3ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,航空会社のITに関わるあらゆるサービスの企画フェーズから導入後の運用保守まで、システムのライ...,業界未経験歓迎副業・WワークOK年間休日120日以上英語完全週休2日制土日祝休み服装自由
117,NSW株式会社,企業名 ＮＳＷ株式会社 求人名 [SVBI]データマネジメント プロジェクトマネージャ【独立...,必要な経験・能力等 【必須】システム開発などPM/PL経験３年以上 ※データマネジメント領...,配属先情報 【配属予定の組織構成】 約80名（20代：50% 30代：23% 40代：16%...,東京都渋谷区桜丘町31-15 JMFビル渋谷02 NSW株式会社 予定勤務地 東京都渋谷区 ...,"月給36万円～55万円 想定年収 700万円～1,000万円 雇用形態 正社員 期間の定め：...",フレックスタイム制度 就業時間 （1日あたり所定労働時間08時間）フレックスタイム制あり（コ...,休日 休日：124日 （内訳） 完全週休二日制 土曜 日曜 祝日 年末年始5日 その他（長期...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 その他制度 退職金：有 社会保...,試用期間あり 試用期間3ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,データマネジメント領域のPMとして、顧客のデータ戦略を成功に導く仕事です。最新のモダンデータ...,業界未経験歓迎年間休日120日以上退職金あり完全週休2日制土日祝休み
124,JCOM株式会社,仕事内容 経験者募集！在宅勤務OK・時短勤務OK の求人です！ 【雇入れ直後】 【仕事内容】...,応募条件 【必要な経験・資格】 ▼経験 ・データエンジニアまたは関連する職種での実務経験（3...,NaN,東京都千代田区丸の内 JCOM株式会社 【交通手段】 通勤アクセス 各線 東京駅から徒歩1分...,"年俸520万円～840万円 給与 年収 5,200,000円 〜 8,400,000円 【給...",フレックスタイム制度 勤務時間 9:30~17:45（残業：20時間／月程度（担当いただく業...,休日・休暇 完全週休二日制 年間休日123日（2025年度）,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生 【福利厚生】 ...,試用期間あり 3ヶ月~6ヶ月,職種 データエンジニア／スタッフ職／管理職（東京） 雇用形態 正社員 研修・試用期間 3ヶ月...,経験者募集！在宅勤務OK・時短勤務OK の求人です！,NaN
136,NSW株式会社,企業名 ＮＳＷ株式会社 求人名 [SVBI]大阪【未経験可】データマネジメントエンジニア【プ...,必要な経験・能力等 【必須】■ITエンジニア経験3年以上(開発、設計、構築、運用など) ☆デ...,配属先情報 サービスソリューション事業本部 【配属予定の組織構成】 約80名（20代：50%...,大阪府大阪市西区南堀江一丁目18番4号 OsakaMetro南堀江ビル2階 NSW株式会社 ...,月給28万5000円～35万3000円 想定年収 515万円～650万円 雇用形態 正社員 ...,フレックスタイム制度 就業時間 （1日あたり所定労働時間08時間）フレックスタイム制あり（コ...,休日 休日：124日 （内訳） 完全週休二日制 土曜 日曜 祝日 年末年始5日 その他（長期...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 その他制度 退職金：有 社会保...,試用期間あり 試用期間3ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,エンジニアとして、顧客のデータ戦略を成功に導くために、データ基盤構築やデータ分析、データ活用...,業界未経験歓迎年間休日120日以上転勤なし退職金あり完全週休2日制土日祝休み
137,AMBL株式会社,仕事内容: 小売・サービス・金融・通信など、さまざまな業界におけるデータ分析基盤構築、顧客分...,求める人材: ▼必須スキル ・IT業界での就業経験（2年以上） ▼以下いずれか必須（1年以上...,NaN,東京都品川区大崎 AMBL株式会社 勤務地: ・東京都品川区大崎一丁目2番2号 アートヴィレ...,"年俸400万円～600万円 給与: 固定残業代あり：年俸 ￥4,000,000 〜 ￥6,0...",固定時間制 勤務時間・曜日: 09:30～18:30 フルフレックス制 所定労働時間：8h（...,休暇・休日: 土日祝休み ■年間休日125日 ■完全週休2日制（土日祝） ■有給休暇（入社日...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生: 交通費支給 ...,試用期間なし,その他: 【会社情報】 本求人は、「共感型採用」を実施する合同会社イーストタイムズの紹介求人...,【急募★9/1 or 10/1 or 11/1入社限定】座学研修有、データアナリスト・データ...,交通費支給
144,REALITY株式会社,仕事内容 経験者募集！在宅勤務OK・時短勤務OK の求人です！ 【雇入れ直後】 【仕事内容】...,応募条件 【求めるスキル／経験】 ・データエンジニアリングの実務経験 ・データモデリングやデ...,NaN,東京都港区六本木 REALITY株式会社 【交通手段】 通勤アクセス 各線 麻布十番駅から徒...,"年俸500万円～1000万円 給与 年収 5,000,000円 〜 10,000,000円 ...",固定時間制 勤務時間 9:30~18:30（残業：10h~30h／月 ※月によって変動します...,休日・休暇 完全週休2日制（土・日）、祝日、年次有給休暇（入社3カ月後に10日間付与）、夏季...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生 【福利厚生】 ...,試用期間あり 3ヶ月,職種 データエンジニア／バーチャルライブ配信コミュニティアプリ「REALITY」運営会社のデ...,経験者募集！在宅勤務OK・時短勤務OK の求人です！,NaN
150,OPTION X(株),仕事内容: 私たちは、女性の独立や開業を応援するために、 未経験からアートメイクアーティスト...,求める人材: 【必須条件】 ・2アカウント以上のInstagram運用経験がある ・動画撮影...,NaN,東京都中央区銀座1-15-7MAC銀座ビル3階 OPTION X(株) 勤務地: ・9時30...,月給25万円以上 給与: ※経験、実績、能力等によって変動 ※トライアル期間の場合変動あり,勤務時間・曜日: ・業務委託契約のため勤務時間・勤務日数に規定なし ・平日夜や土日祝の勤務可能,休暇・休日: ・業務委託契約のため勤務時間・勤務日数に規定なし,待遇・福利厚生: 【雇用形態・報酬】 ・雇用形態：業務委託 ・固定報酬：月25万円（税別）〜,NaN,その他: 【こんな方が活躍しています！】 これまでの経験を問わず、様々な経験をしている方が活...,女性の開業や独立を応援するアートメイクスクールのInstagram総合ディレクター担当アピー...,在宅OK
159,NSW株式会社,企業名 ＮＳＷ株式会社 求人名 [SVBI]大阪：データマネジメント プロジェクトマネージャ...,必要な経験・能力等 【必須】システム開発などPM/PL経験３年以上 ※データマネジメント領域...,配属先情報 【配属予定の組織構成】 約80名（20代：50% 30代：23% 40代：16%...,大阪府大阪市西区南堀江一丁目18番4号 OsakaMetro南堀江ビル2階 NSW株式会社 ...,"月給36万円～55万円 想定年収 700万円～1,000万円 雇用形態 正社員 期間の定め：...",フレックスタイム制度 就業時間 （1日あたり所定労働時間08時間）フレックスタイム制あり（コ...,休日 休日：124日 （内訳） 完全週休二日制 土曜 日曜 祝日 年末年始5日 その他（長期...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 その他制度 退職金：有 社会保...,試用期間あり 試用期間3ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,データマネジメント領域のPMとして、顧客のデータ戦略を成功に導く仕事です。最新のモダンデータ...,業界未経験歓迎年間休日120日以上転勤なし退職金あり完全週休2日制土日祝休み
168,FPTジャパンホールディングス株式会社,仕事内容: ＦＰＴジャパンホールディングス株式会社について 「テクノロジーで社会課題を解決し...,求める人材: 必須要件 【下記いずれか必須】 * 本社/企画業務経験がある方（2年以上） *...,NaN,福岡県福岡市博多区博多駅前 FPTジャパンホールディングス株式会社 勤務地: 812-001...,年俸400万円～800万円 給与: 年収 400万円 〜 800万円 （年俸制制度 報酬額の...,固定時間制 勤務時間・曜日: * 9:00-18:00 （所定労働時間：8時間0分、休憩時間...,休暇・休日: * 完全週休2日（土曜日、日曜日、祝日） * 夏季休暇、年末年始休暇 * 有給...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生: 待遇・福利厚...,試用期間あり 試用期間：6か月 試用期間中の労働条件：同条件,その他: 求人について 本求人は、株式会社エイジレスが雇用主企業からの委託を受けて行う人材紹...,未経験から福岡でコンサルタントへ。急成長企業で大手企業の経営変革に挑戦する第二のキャリアを実...,交通費支給
173,KINTOテクノロジーズ株式会社,企業名 ＫＩＮＴＯテクノロジーズ株式会社 求人名 大阪【クラウドエンジニア】100年に一度の...,必要な経験・能力等 【必須】■AWS環境の設計・構築・運用経験■Infrastructure...,配属先情報 Cloud Infrastructureグループ ★AWSを主としたクラウドイン...,大阪府大阪市中央区南船場4丁目3番11号大阪豊田ビル４F KINTOテクノロジーズ株式会社 ...,"月給32万4000円以上 想定年収 660万円～1,200万円 雇用形態 正社員 期間の定め...",フレックスタイム制度 就業時間 （1日あたり所定労働時間08時間）フレックスタイム制あり（コ...,休日 休日：121日 （内訳） 完全週休二日制 土曜 日曜 祝日 年末年始5日 その他（） ...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 その他制度 退職金：有 社会保...,試用期間あり 試用期間3ヶ月。,採用企業情報・求人取扱いエージェント ■求人取扱いエージェント リクルートエージェント ht...,トヨタグループ全体のクラウド活用推進や開発速度の向上に貢献するため、トヨタグループ各社のプロ...,年間休日120日以上退職金あり完全週休2日制土日祝休み
174,AMBL株式会社,仕事内容: 小売・サービス・金融・通信など、さまざまな業界におけるデータ分析基盤構築、顧客分...,求める人材: ▼必須スキル ・IT業界での就業経験（2年以上） ▼以下いずれか必須（1年以上...,NaN,東京都品川区大崎一丁目2番2号アートヴィレッジ大崎セントラルタワー10階 AMBL株式会社 ...,月給25万円～40万円 給与: <給与> 想定年収：400万円～600万円 月給：25万円～...,シフト制 勤務時間・曜日: 〈勤務時間〉 09:30~18:30 夜間勤務：なし 月間平均残...,休暇・休日: 〈休日休暇〉 休日：土日祝休み 年間休日：125日 休暇制度：年末年始休暇、夏...,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生: 〈福利厚生・...,試用期間なし,その他: ＜選考に関して＞ カジュアル面談の有無 :なし 会社説明会の有無 :なし 適性テス...,【急募★10/1～12/1入社限定】座学研修有、データアナリスト・データ基盤構築エンジニア◆...,NaN
179,JCOM株式会社,仕事内容: ★大型の投資案件に関する、戦略的位置付け定量・定性面での投資の妥当性等を網羅的に...,求める人材: 【必要な経験・資格】 （経験） 以下いずれかのご経験がある方 ① 事業会社等で...,NaN,東京都千代田区 JCOM株式会社 勤務地: 東京都千代田区丸の内1-8-1 丸の内トラストタ...,月給35万円～82万5000円,フレックスタイム制度 勤務時間・曜日: ■勤務時間 標準就業時間帯：9:30－17:45、休...,NaN,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生: ■休日 完全...,試用期間あり 試用期間：3か月 試用期間中の労働条件：同条件,その他: この求人への応募は、株式会社ギークニアにて面談を実施した後の応募となります。 ギー...,IT実務の経験者向け/J:COMグループ 投資評価・妥当性審査 網羅的なレビューと専門性活か...,在宅OK
197,FPTジャパンホールディングス株式会社,仕事内容: ＦＰＴジャパンホールディングス株式会社について 「テクノロジーで社会課題を解決し...,求める人材: 応募要件 下記、いずれかの経験がある方 - 財務会計、管理会計、経営管理領域に...,NaN,東京都港区芝公園 FPTジャパンホールディングス株式会社 勤務地: 【本社】東京都港区芝公園...,"年俸400万円～2500万円 給与: 年収 4,000,000 円 - 25,000,000...",固定時間制 勤務時間・曜日: 9:00〜18:00 （所定労働時間：8時間0分、休憩時間：6...,休暇・休日: 週2日,【保険制度】 ・雇用保険 ・労災保険 ・健康保険 ・厚生年金 待遇・福利厚生: 待遇・福利厚...,試用期間あり 試用期間：6か月 試用期間中の労働条件：同条件,その他: 求人について 本求人は、株式会社エイジレスが雇用主企業からの委託を受けて行う人材紹...,経営管理のDXを、構想から実現まで完遂する。最先端EPMで企業の意思決定を進化させる、その舞...,即日勤務OK交通費支給

In [ ]:
# 省略表記の確認
print(
    f"省略表記の件数: {df['会社名'].str.contains('(株)|(有)|㍿|（株）|（有）', regex=True, na=False).sum()}"
)

省略表記の件数: 198

/tmp/ipykernel_2654/2595050042.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  f"省略表記の件数: {df['会社名'].str.contains('(株)|(有)|㍿|（株）|（有）', na=False).sum()}"

02_「勤務地」項目の確認

In [1]:
import pandas as pd

# スクレイピング結果csvを読み込んで、「勤務地」データ確認
df = pd.read_csv("/app/data/rikunabi.csv")

In [ ]:
# 勤務地の表記確認
print(f"先頭20件:\n{df['会社名'].head(20)}")
print("------------------------------------------------------")
print(f"会社名の出現回数:\n{df['会社名'].value_counts().head(30)}")
print("------------------------------------------------------")
print(f"末尾20件:\n{df['会社名'].tail(20)}")